language: node_js
sudo: required
node_js:
  - 6
services:
  - redis-server
  - mongodb
before_install:
  - sudo apt-get update
  - sudo apt-get install --assume-yes apache2-utils
  - npm config set strict-ssl false
install: npm install
env:
  - MONGODB_VERSION=2.4
  - MONGODB_VERSION=3.2
script:
  - make test-once
after_script: make test-coveralls
